// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type User struct {
	ID                int64  `json:"id"`
	Email             string `json:"email"`
	EncryptedPassword string `json:"encrypted_password"`
}
