name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 467958
          POSTGRES_DB: microapp
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
      id: go
    
    - name: Check out code into the go module directory
      uses: actions/checkout@v2

    - name: Install golang-migrate
      run: |
        curl -L https://packagecloud.io/golang-migrate/migrate/gpgkey | sudo apt-key add -
        sudo sh -c 'echo "deb https://packagecloud.io/golang-migrate/migrate/ubuntu/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/migrate.list'
        sudo apt-get update
        sudo apt-get install -y migrate

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
